package turbomq.testing;

import turbomq.common.NodeId;

import java.util.*;

/**
 * Test harness for building deterministic Raft cluster scenarios.
 *
 * Manages a simulated N-node cluster with controlled message delivery,
 * virtual time, and network fault injection. Enables reproducible
 * testing of leader election, log replication, and failure recovery.
 *
 * Usage:
 * <pre>
 * var harness = RaftTestHarness.create(3);  // 3-node cluster
 * harness.triggerElectionTimeout(NodeId.of(0));
 * harness.deliverAllMessages();
 * harness.deliverAllMessages();  // responses
 * assertThat(harness.getLeader()).isNotNull();
 * </pre>
 */
public final class RaftTestHarness {

    private final SimulatedNetwork network;
    private final SimulatedClock clock;
    private final List<NodeId> nodeIds;

    public RaftTestHarness(int clusterSize) {
        this.network = new SimulatedNetwork();
        this.clock = new SimulatedClock();
        this.nodeIds = new ArrayList<>();

        for (int i = 0; i < clusterSize; i++) {
            NodeId nodeId = NodeId.of(i);
            nodeIds.add(nodeId);
            network.registerNode(nodeId);
        }
    }

    public static RaftTestHarness create(int clusterSize) {
        return new RaftTestHarness(clusterSize);
    }

    public SimulatedNetwork network() { return network; }
    public SimulatedClock clock() { return clock; }
    public List<NodeId> nodeIds() { return Collections.unmodifiableList(nodeIds); }

    /** Get the majority quorum size for this cluster. */
    public int quorumSize() {
        return nodeIds.size() / 2 + 1;
    }

    /** Get all peer IDs for a given node (all nodes except itself). */
    public List<NodeId> peersOf(NodeId nodeId) {
        return nodeIds.stream()
                .filter(id -> !id.equals(nodeId))
                .toList();
    }

    /** Deliver all pending messages in the network. */
    public int deliverAllMessages() {
        return network.deliverAll();
    }

    /**
     * Run a full message delivery round: deliver all pending,
     * then deliver any messages generated by processing those.
     * Repeats up to maxRounds to reach quiescence.
     *
     * @return total messages delivered across all rounds
     */
    public int stabilize(int maxRounds) {
        int total = 0;
        for (int i = 0; i < maxRounds; i++) {
            int delivered = network.deliverAll();
            if (delivered == 0) break;
            total += delivered;
        }
        return total;
    }
}
